name: Selenium CI Pipeline

on: [push]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Install Chromium and Driver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Run Selenium Tests
      run: python selenium_test.py

